### ISSUE TITLE
Htmleditor not showing up in Edge browser

### ISSUE THREAD

**Issue by deepthitalasila** [PaulNieuwelaar/htmleditor#2]
Hi Paul ,

This is a awesome solution and was able to use it for one of our requirements . Current blocker we have is , html editor doesn't show up on edge browser and I could see below error 

 HTTP404: NOT FOUND  'webresources/mag_/htmleditor/skins/moono/editor_iequirks.css'

It would be great if you can fix this issue !!

Thanks ,
Deepthi

**Comment by PaulNieuwelaar** [comment]
Hi Deepthi, 

That's weird, when I try with Edge it doesn't require that file, but I may be using a different version or something. This 'iequirks' file is included in the base CKEditor package, but it's never been needed before, but if it's needed for Edge now, I can add it into the solution. 

Since it's working for me even without the iequirks file, I can't actually confirm if this fixes the issue, so before I release an updated version, could you please add a new web resource into your system manually, and add the css from here:
https://github.com/PaulNieuwelaar/htmleditor/blob/master/HTMLEditor/HTMLEditor.Web/mag_/htmleditor/skins/moono/editor_iequirks.css

Make sure the web resource name exactly matches: mag_/htmleditor/skins/moono/editor_iequirks.css

If it fixes the issue, let me know, and I'll release a new solution containing this file.

Cheers,
Paul

**Comment by deepthitalasila** [comment]
Thanks for the quick response Paul . Did this solutions work on Edge before ? adding this css did not fix issue . I could see that html is rendered but hidden

**Comment by deepthitalasila** [comment]
It worked looks like issue is with version of ckeditor .

**Comment by PaulNieuwelaar** [comment]
Hi Deepthi,

Sorry, just to confirm, did adding the css file I suggested fix the issue, or did you have to do something else?

Cheers,
Paul

**Comment by deepthitalasila** [comment]
Hi ,

I have get latest version of ckeditor

Thanks
Deepthi

________________________________

**Comment by PaulNieuwelaar** [comment]
Thanks, which files specifically did you need to update? I updated all the CKEditor files in the solution not long ago to the latest version, so if another update is required again I'd like to make sure the solution and files are all up to date.

Cheers,
Paul
